---
version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    # env_file:
    #   - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOTUSERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    ports:
      - 27017:27017
    volumes: 
      - mongodb_data:/vagrant/data/mongodb
    
volumes:
  mongodb_data: